# Generated by Django 3.0.4 on 2020-03-17 07:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail_graphql.models
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0046_auto_20200317_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TommywalkerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='本文')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_graphql.models.GraphQLEnabledModel, 'wagtailcore.page'),
        ),
    ]
