# Generated by Django 2.1.7 on 2019-08-26 03:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='articles.ArticlePageTag', to='taggit.Tag', verbose_name='タグ'),
        ),
    ]
