# Generated by Django 2.1.7 on 2019-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateTimeField(verbose_name='投稿日'),
        ),
    ]
