# Generated by Django 2.1.7 on 2019-09-03 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20190903_0144'),
        ('articles', '0002_auto_20190902_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='author.AuthorPage', verbose_name='著者'),
        ),
    ]
