# Generated by Django 2.1.7 on 2019-09-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='family_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='is_surname_first',
            field=models.BooleanField(blank=True, null=True, verbose_name='姓が先の表記'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='middle_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ミドルネーム'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='表示名'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='nickname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='use_nickname',
            field=models.BooleanField(blank=True, null=True, verbose_name='ニックネームの使用'),
        ),
    ]
