# Generated by Django 2.1.7 on 2019-08-20 10:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail_graphql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0042_auto_20190820_1010'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappinessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='投稿日')),
                ('first', models.CharField(max_length=25, verbose_name='一つ目のよいこと')),
                ('second', models.CharField(max_length=25, verbose_name='二つ目のよいこと')),
                ('third', models.CharField(max_length=25, verbose_name='三つ目のよいこと')),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='画像')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_graphql.models.GraphQLEnabledModel, 'wagtailcore.page'),
        ),
    ]
