# Generated by Django 2.1.7 on 2019-09-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterpage',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='概要'),
        ),
    ]
