name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install python3-dev libmysqlclient-dev libreadline-dev libsqlite3-dev
        pip install pipenv zappa
        git clone git://github.com/yyuu/pyenv.git ~/.pyenv
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 3.7.6
        pyenv local 3.7.6
        pipenv shell
        pipenv install
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pipenv run tests
    - name: Install awscli
      run: |
        mkdir -p ~/.aws
        touch ~/.aws/config
        echo "[default]\nregion = us-east-1\noutput = json" > ~/.aws/config
        touch ~/.aws/credentials
        echo "[default]\naws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key = ${{ secrets.AWS_SECRET_KEY_ID }}" > ~/.aws/credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy for Development Environment
      run: |
        zappa update dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        NETLIFY_HOOKS_URL: ${{ secrets.NETLIFY_HOOKS_URL }}
        DJANGO_STAGING_USER: ${{ secrets.DJANGO_STAGING_USER }}
        DJANGO_STAGING_PASSWORD: ${{ secrets.DJANGO_STAGING_PASSWORD }}
        DJANGO_STAGING_HOST: ${{ secrets.DJANGO_STAGING_HOST }}
